version: "3.8"

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    environment:
      - PMA_HOST=${SQL_HOST}
      - PMA_USER=${SQL_USER}
      - PMA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  jobs:
    build:
      context: .
      dockerfile: jobs/Dockerfile
    container_name: jobs
#    tty: true
    volumes:
      - storage:/mnt/storage
      - share:/mnt/share
      - ./jobs:/app/jobs
    networks:
      - backend

volumes:

  storage:
    driver: local
    driver_opts:
      type: cifs
      device: ${MOUNT_STORAGE}
      o: ${MOUNT_OPTIONS}

  share:
    driver: local
    driver_opts:
      type: cifs
      device: ${MOUNT_SHARE}
      o: ${MOUNT_OPTIONS}

networks:
  backend:
  frontend: